theme: jekyll-theme-minimal
title: SoftDes Final Project<br/> Interactive Game Design
description: "Fall semester 2020 - Final project: Incorporate user input and apply what has been used throughout this semester to make something fun. "
